version: "3"
services:
  aws-cdk:
    build:
      context: ./
      dockerfile: Dockerfile
    image: aws-cdk
    volumes:
      - ./.aws/:/root/.aws/
      - .:/workspace
      - /workspace/node_modules
      - /workspace/handlers/packages
    container_name: aws-cdk
    tty: true
    env_file:
      - .env
